http:
  routers:
    grafana:
      entrypoints:
        - "web"
      rule: "PathPrefix(`/grafana/`)"
      service: "grafana"

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://gagglemon-grafana.:3000"
