http:
  routers:
    node-exporter:
      entrypoints:
        - "metrics"
      rule: "Path(`/node/metrics`)"
      middlewares:
        - "node-exporter-stripprefix"
      service: "node-exporter"

    blackbox-exporter:
      entrypoints:
        - "metrics"
      rule: "Path(`/blackbox/probe`) || Path(`/blackbox/metrics`)"
      middlewares:
        - "blackbox-exporter-stripprefix"
      service: "blackbox-exporter"

    grafana:
      entrypoints:
        - "web"
      rule: "PathPrefix(`/grafana/`)"
      service: "grafana"

  middlewares:
    node-exporter-stripprefix:
      stripPrefix:
        prefixes:
          - "/node"

    blackbox-exporter-stripprefix:
      stripPrefix:
        prefixes:
          - "/blackbox"

  services:
    node-exporter:
      loadBalancer:
        servers:
          - url: "http://gagglemon-node-exporter.:9100"

    blackbox-exporter:
      loadBalancer:
        servers:
          - url: "http://gagglemon-blackbox-exporter.:9115"

    grafana:
      loadBalancer:
        servers:
          - url: "http://gagglemon-grafana.:3000"
