# traefik "static" config

# development env setup
# so no tls anything
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
  metrics:
    address: ":9011"

# dynamic config
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
    debugLogGeneratedTemplate: true
